apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: ebs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      serviceAccountName: portainer-sa
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
            - containerPort: 9443
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: portainer-admin-secret
                  key: admin-user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portainer-admin-secret
                  key: admin-password
          volumeMounts:
            - name: portainer-data
              mountPath: /data
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock