apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-pv
  namespace: ebs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/k8s/kibana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-pvc
  namespace: ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi