apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: ebs
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      name: http
    - port: 9443
      targetPort: 9443
      name: https
  selector:
    app: portainer