apiVersion: v1
kind: Secret
metadata:
  name: portainer-admin-secret
  namespace: ebs
type: Opaque
stringData:
  # Replace with your desired credentials
  admin-user: admin
  admin-password: Ebs@Church!Admin?2025